### PR TITLE
Remove MQTT code and replace it by a simple callback

### LINKED ISSUE #1: substitute mqtt code by callback function
* [x] callback with obis code and string value
* [x] print to serial

### PR DESCRIPTION
**Pull request by michaelosthege**
Closes #1

### CODE REVIEW

**Comment by marost0903** [comment]
reviewed successfully
tried to build - succeeded 
and upload - ok
adding debugging info for serial monitor output would be helpful from my pov

**Comment by marost0903** [comment]
done

**Comment by michaelosthege** [comment]
@marost0903 "Close" means to reject the changes. Please hit the green "Merge pull request" :)

**Comment by marost0903** [comment]
merge confirmed

**Pull request merged**
